spring:
    application:
        name: rabbit_mq
    rabbitmq:
        host: "localhost"
        port: 5672
        username: "admin"
        password: "admin"
        retry:
            enabled: true
            max-attempts: 3
            delay: 1000

rabbitmq:
    retry:
        delay-in-ms: 1000
        count: 3
        
com:
    arturo:
        projects:
            rabbitmq:
                config:
                    queue:
                        name: "orders"
                        exchange: "orders"
                        routing: "orders"  



